services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
