services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    restart: always
    healthcheck:
      test:
        [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5m
      retries: 10
      start_period: 30s
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    container_name: rabbitmq
    env_file: .env
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 1m
      retries: 5
      start_period: 45s
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
  redis:
    image: redis:7.2.4-alpine3.19
    container_name: redis
    env_file: .env
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli" "ping" ]
      interval: 20s
      timeout: 1m
      retries: 5
      start_period: 45s
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
