environment:
  access_token_secret_key: ${ACCESS_TOKEN_SECRET_KEY}
  refresh_token_secret_key: ${REFRESH_TOKEN_SECRET_KEY}
debug: false
spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  application:
    name: open_music_api
  cache:
    cache-names: like_cache
    redis:
      time-to-live: 15m
  jackson:
    mapper:
      allow-coercion-of-scalars: false
      apply-default-values: false
      default-view-inclusion: false
      use-static-typing: true
  jpa:
    database: postgresql
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
  main:
    banner-mode: off
logging:
  config: classpath:log4j2.yml
  charset:
    file: UTF-8
    console: UTF-8
  file:
    name: log.jsonl
    path: logs/
  level:
    root: info
    sql: info
    web: info
    org:
      hibernate: info
      springframework:
        orm.jpa.JpaTransactionManager: debug
  log4j2:
    config:
      override: classpath:log4j2.yml
