services:
  open-music-api:
    container_name: open-music-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - postgres
    env_file:
      - .env
    links:
      - postgres
    ports:
      - ${PORT}:${PORT}
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.19
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', '${POSTGRES_DB}', '-U', '${POSTGRES_USER}']
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 5s
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    # volumes:
    #   - postgres:/var/lib/postgresql/data
    networks:
      - postgres
# volumes:
#   postgres:
#     name: postgres
networks:
  postgres:
    name: postgres
